image:
  repository: tccr.io/truecharts/emby
  pullPolicy: IfNotPresent
  tag: 4.7.8.0@sha256:d866269decedca91bf9c47293fba9cb4eb95ce984b5f985a3f9d9fa626980163

securityContext:
  readOnlyRootFilesystem: false

service:
  main:
    ports:
      main:
        port: 10079
        targetPort: 8096

persistence:
  config:
    enabled: true
    mountPath: "/config"

portal:
  enabled: true
