image:
  repository: tccr.io/truecharts/emby
  pullPolicy: IfNotPresent
  tag: 4.7.8.0@sha256:a53458c16b756c1d914939d0a0d2921e13e5f8326662ce2d2191281f2f5f36b7

securityContext:
  readOnlyRootFilesystem: false

service:
  main:
    ports:
      main:
        port: 10079
        targetPort: 8096

persistence:
  config:
    enabled: true
    mountPath: "/config"

portal:
  enabled: true
